apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: maxmcf13/mydb:latest
    ports:
    - containerPort: 3306
    env: 
    - name: MYSQL_DATABASE
      value: flask-db
    - name: MYSQL_ROOT_PASSWORD
      value: password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP